name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Create NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> ./.npmrc
          echo "@blocklessnetwork:registry=https://npm.pkg.github.com" >> ./.npmrc

      - name: Install dependencies
        run: npm i

      - name: Prettier
        run: npm run format

      - name: Test
        run: npm test
